name: Playwright Regression CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  automation-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v4

    - name: Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Project Dependencies
      run: npm ci

    - name: Install Playwright System Dependencies & Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright Tests
      run: npx playwright test

    - name: Publish Test Report HTML Artifact
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-execution-report
        path: playwright-report/
        retention-days: 30